jobs:
  include:
    - stage: "Test"
      name: "Use custom image 2305-image3"
      vm:
        use:
          name: 3005-image6

    - stage: "Test"
      name: "Use custom image 2305-image4"
      vm:
        use:
          name: 3005-image14
