jobs:
  include:
    - stage: create image
      os: linux
      dist: focal
      language: generic
      vm:
        create:
          name: 3005-image3
      before_install:
        - sudo apt-get -y install libxml2-dev
      addons:
        apt:
          update: true
    - stage: use custom image
      vm:
        use: 3005-image3
      script:
        - echo "Running job with custom image"
